---
title: "integrate_observations"
output: html_document
---

```{r}
library(raster)
library(rgdal)
library(sf) # https://github.com/rstudio/cheatsheets/blob/main/sf.pdf
library(here)
library(tidyverse)
```

```{r}
presence <- sf::read_sf(here("oaks","oaks_data","oaks_sample.geojson"))  
absence <- sf::read_sf(here("oaks","oaks_data","oaks_absences.geojson")) 

env_stack <- raster::stack(here("oaks","env_layers","sb_env_stack.grd"))

# match all CRS
presence <- st_transform(presence,crs(env_stack))
absence <- st_transform(absence, crs(env_stack))
```


```{r}
df_presence<- st_coordinates(presence) %>% 
  as_data_frame() %>% 
  mutate(presence=1) 

df_absence<- st_coordinates(absence) %>% 
  as_data_frame() %>% 
  mutate(presence=0)

pres_abs <- bind_rows(df_absence,df_presence) %>% 
  mutate(ID = 1:n()) %>% 
  relocate(ID)

rm(presence, absence, df_absence,df_presence)
```


```{r}
 # extract raster values for points
env_info <- raster::extract(env_stack, 
                            pres_abs %>% select(X,Y), 
                            df=TRUE)

oaks <- left_join(pres_abs,env_info, by="ID") %>% 
    relocate(presence) %>% 
  select(!ID)

#write_csv(oaks, here("oaks","oaks_data","oaks_pres_abs_env.csv"))
```

