---
title: "oaks_env_pred_exploration"
author: "Carmen Galaz-García"
date: "1/21/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

librarian::shelf(
  here, 
  rgdal, 
  raster,
  sdmpredictors, 
  sf, 
  tidyr)
```

```{r}
# ------ auxiliary sets and functions ------------

# Santa Barbara shapefile
sb <- readOGR(here("oaks",
                   "sb_shapefile",
                   "SB_only.shp"))

# ------------------------------------------------------------

# shape needs to be opened via readOGR() in library(rgdal) 
crop_shape <- function(ref_raster , shape){
  new_shape <- spTransform(shape, crs(ref_raster))
  return(mask(crop(x= ref_raster, y=st_bbox(new_shape)),new_shape))
}

```

## Round 1: Species Distribution Modeling Predictor Datasets (SDMP)

```{r}
# ----- EXPLORE AVAILABLE LAYERS -----
# To see how to explore the different datasets available through sdmp see jaguar_prepare_data.Rmd

# choose layers after some inspection and perhaps consulting literature
env_layers_vec <- c("WC_alt", # altitude
                    "WC_bio1", # Annual mean temperature
                    "WC_bio2", # Mean diurnal temperature range
                    "WC_bio13", # Precipitation of wettest month
                    "WC_bio14", # Precipitation of driest month
                    "WC_bio15", # Precipitation seasonality
                    #"ER_aridityIndexThornthwaite", #T hornthwaite aridity index
                    "ER_tri", # Terrain roughness index
                    "ER_topoWet") # Topographic wetness

# get layers
env_stack <- load_layers(env_layers_vec)
rm(env_layers_vec)

# interactive plot layers, hiding all but first (select others)
# mapview(env_stack, hide = T) # makes the html too big for Github
plot(env_stack, nc=2)
```
### SDMP masking
```{r}
# -----------------------------------------------------------------------------
# MASK ENV VARIABLES STACK 
save_env_stack <- FALSE

env_stack_sdmp <- crop_shape(env_stack,sb)

if (save_env_stack){
  env_stack_grd <- file.path(data_dir, "sdmp_env_stack.grd")
  writeRaster(env_stack_sdmp, env_stack_grd, overwrite=T)  
  env_stack <- stack(env_stack_grd)
  rm(env_stack_grd)
}
rm(save_env_stack)

plot(env_stack_sdmp, nc=2)
```

## Round 2: Google Earth Engine datasets

```{r}
# +++++++++++++++  ELEVATION  +++++++++++++++++
# https://developers.google.com/earth-engine/datasets/catalog/USGS_3DEP_10m
# ----------------------------------------------------------------------
raw_elevation <- raster(here("oaks/env_layers/GEE/ca_elevation.tif"))
# 30m ? resolution
elev <- crop_shape(raw_elevation, sb)
rm(raw_elevation)

# +++++++++++++++  TEMPERATURE  +++++++++++++++++
# https://developers.google.com/earth-engine/datasets/catalog/WORLDCLIM_V1_BIO
# ----------------------------------------------------------------------
raw_temp_season <-raster(here("oaks/env_layers/GEE/sb_tempseason.tif"))
temp_season <- crop_shape(raw_temp_season, sb)
rm(raw_temp_season)
# ----------------------------------------------------------------------
raw_meantemp <- raster(here("oaks/env_layers/GEE/ca_mean_temp.tif"))
# 100 m resolution
meantemp <- crop_shape(raw_meantemp, sb)
rm(raw_meantemp)
# ----------------------------------------------------------------------
raw_mean_coldest <-raster(here("oaks/env_layers/GEE/sb_mean_coldest.tif"))
mean_coldest <- crop_shape(raw_mean_coldest, sb)
rm(raw_mean_coldest)
# ----------------------------------------------------------------------
raw_mean_warmest <-raster(here("oaks/env_layers/GEE/sb_mean_warmest.tif"))
mean_warmest <- crop_shape(raw_mean_warmest, sb)
rm(raw_mean_warmest)

# +++++++++++++++  PRECIPITATION +++++++++++++++++
# https://developers.google.com/earth-engine/datasets/catalog/WORLDCLIM_V1_BIO
# ----------------------------------------------------------------------
raw_annual_precip <-raster(here("oaks/env_layers/GEE/sb_annual_precip.tif"))
annual_precip <- crop_shape(raw_annual_precip, sb)
rm(raw_annual_precip)
# ----------------------------------------------------------------------
raw_wettest_month <-raster(here("oaks/env_layers/GEE/sb_wettest_month.tif"))
wettest_month <- crop_shape(raw_wettest_month, sb)
rm(raw_wettest_month)
# ----------------------------------------------------------------------
raw_driest_month <-raster(here("oaks/env_layers/GEE/sb_driest_month.tif"))
driest_month <- crop_shape(raw_driest_month, sb)
rm(raw_driest_month)
# ----------------------------------------------------------------------
```

```{r}
plot(elev, main="Elevation")
# --------------------------------------------------
plot(temp_season, main="Temperature Seasonality")
plot(meantemp, main="Mean Annual Temp")
plot(mean_coldest, main="Mean temperature of coldest month")
plot(mean_warmest, main="Mean temperature of warmest month")
# --------------------------------------------------
plot(annual_precip, main="Annual Precipitation")
plot(driest_month, main="Precipitation of driest month")
plot(wettest_month, main="Precipitation of wettest month")
```


```{r}
folder <- here("oaks","env_layers","sb_env_layers")
raster::writeRaster(temp_season, file.path(folder,"sb_temp_seasonality.tif"))
raster::writeRaster(elev, file.path(folder,"sb_elevation.tif"))
raster::writeRaster(meantemp, file.path(folder,"sb_meantemp.tif"))
```


```{r}
# ----------------------------------------------------------------------
# Aridity Index (2017), the one used in TNC ecosystem map
raw_arid <- raster(here("oaks","env_layers","ca_aridity_index.tif"))
arid <- crop_shape(raw_arid, sb)
rm(raw_arid)
# ----------------------------------------------------------------------
# Climate layer created from WorldClim data (30 yr average)
raw_clim <- raster(here("oaks","env_layers","ca_clim_2019.tif"))
clim <- crop_shape(raw_clim, sb)
rm(raw_clim)

# ----------------------------------------------------------------------
plot(clim, main="Climate")
plot(arid, main="Aridity Index")
```


## ENV PREDICTOR SELECTION

```{r}
# SELECTED LAYERS

elev <- projectRaster(from = elev, to= arid, method='bilinear')

temp_season <- projectRaster(from=temp_season, to=arid, method="bilinear")
meantemp <- projectRaster(from = meantemp, to= arid, method='bilinear')
mean_coldest <- projectRaster(from = mean_coldest, to= arid, method='bilinear')
mean_warmest <- projectRaster(from = mean_warmest, to= arid, method='bilinear')

annual_precip <- projectRaster(from = annual_precip, to=arid, method = "bilinear")
driest_month <- projectRaster(from= driest_month, to=arid, method="bilinear")
wettest_month <- projectRaster(from=wettest_month, to=arid, method = "bilinear")


env_pred <- stack(elev, 
                  arid, 
                  temp_season, meantemp, mean_coldest, mean_warmest,
                  annual_precip, driest_month, wettest_month)
names(env_pred) <- c("elevation","aridity",
                     "temp_seasonality","mean_temp","coldest_month","warmest_month",
                     "annual_precipitation","driest_month","wettest_month")

plot(env_pred)
```


```{r}
# Save stack

# path for env variables masked raster stack 
env_stack_grd <- file.path(here(), 
                           "oaks",
                           "env_layers",
                           "sb_env_stack.grd")

if (!file.exists(env_stack_grd)){
  writeRaster(env_pred, env_stack_grd, overwrite=T)  
}
rm(env_stack_grd)
```
